development:
  adapter: postgresql
  encoding: utf8
  database: hustle
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hustle_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: hustle
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST
